################
# TP CONTROLLER
################

training_correction.tp_controller:
  menu_name: cockpit
  title: 'TP Controller'
  route_name: training_correction.tp_controller
  weight: 1

training_correction.tp_entity:
  menu_name: cockpit
  title: 'TP Entité'
  route_name: training_correction.tp_entity
  weight: 2

training_correction.tp_service:
  menu_name: cockpit
  title: 'TP Services'
  route_name: training_correction.tp_service
  weight: 3

training_correction.tp_form:
  menu_name: cockpit
  title: 'TP Form'
  route_name: training_correction.tp_form
  weight: 4
